### PR TITLE
Don't ping file reviewers if they are the PR author

### PR DESCRIPTION
**Pull request by jyn514**
e.g. https://github.com/rust-lang/rust/pull/75079#issuecomment-667749374

### CODE REVIEW

**Comment by jyn514** [comment]
The test suite is confusing me a little, does anyone know how I would test this?

**Comment by jyn514** [comment]
ping @Mark-Simulacrum - is this waiting on me? I still run into this a lot.

**Comment by Mark-Simulacrum** [comment]
I don't know how to test this, but I'm not too worried about doing so. This seems fine to land to me.

**Comment by jyn514** [comment]
This does not seem to have worked :( https://github.com/rust-lang/rust/pull/85052#issuecomment-834760674

**Pull request merged**
