### PR TITLE
Update global doc global alert list

### PR DESCRIPTION
**Pull request by XAMPPRocky**
r? @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+

**Comment by GuillaumeGomez** [comment]
Ah, might not have bors here... Ping @pietroalbini ! :)

**Comment by GuillaumeGomez** [comment]
I think you can squash now. ;)

**Comment by XAMPPRocky** [comment]
I did this through GitHub's UI, which has no such option that I know of unless you're the person actually merging.

**Comment by GuillaumeGomez** [comment]
Ah right. Then don't worry, the merger will then I guess.

**Pull request merged**
