### PR TITLE
Add config file for Clippy

### PR DESCRIPTION
**Pull request by flip1995**
Clippy PR queue got pretty long recently and we hope that by assigning someone to each PR we can handle the workload better.

@Manishearth @matthiaskrgr @phansch @yaahc I added you to the reviewers list. If you don't want to get assigned automatically, let me know and I can remove you again.

@rust-lang/clippy If someone else from the Clippy team wants to get assigned to PRs for review, also let me know and I'll add you to the list.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Please ping me when you're ready for this to be merged.

**Comment by Manishearth** [comment]
+1 from my side

**Comment by flip1995** [comment]
@Mark-Simulacrum we're ready to merge this.

**Comment by Mark-Simulacrum** [comment]
CI on master should auto-deploy this.

**Pull request merged**
