### PR TITLE
Remove myself from the set of "libs" reviewers

### PR DESCRIPTION
**Pull request by joshtriplett**
I'm not on the libs team.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
FWIW these are reviewers appropriate for the standard library, and if you feel you can review such code there's no reason not to be on the list.

**Comment by joshtriplett** [comment]
@Mark-Simulacrum I feel comfortable reviewing such code, but in many cases, I've felt like I'd be overstepping to approve something rather than getting someone on the libs team to review. In other words, I feel like I'm getting assigned to things for which I *could* r+ but for which I feel like I don't have the necessary authority to r+.

**Comment by Mark-Simulacrum** [comment]
Hm, so current policy is that library *implementation* review is under compiler team, whereas library API is under library team. Often PRs touch on both, but not always.

I believe that anyone who feels comfortable approving code should feel free to do so (obviously, if you overreach, we'll likely need to have a conversation, but I don't expect that).

See also https://blog.rust-lang.org/inside-rust/2020/07/02/Ownership-Std-Implementation.html for some more details on this.

**Comment by joshtriplett** [comment]
> Hm, so current policy is that library implementation review is under compiler team, whereas library API is under library team.

Well, I'm also not on the compiler team. :)

> I believe that anyone who feels comfortable approving code should feel free to do so

So, effectively, anything that doesn't add API surface area is reasonable to review? If that's the case, then feel free to close this, and I'll review with that premise in mind.

**Comment by Mark-Simulacrum** [comment]
Yes, that's true. Even API surface expansion usually has implementation to review; usually the policy I follow is to perform that review, and then say something like "r=me on implementation; r? @some-libs-team-member on API"

**Comment by joshtriplett** [comment]
On Thu, Sep 24, 2020 at 04:48:29PM -0700, Mark Rousskov wrote:
> Yes, that's true. Even API surface expansion usually has implementation to review; usually the policy I follow is to perform that review, and then say something like "r=me on implementation; r? @some-libs-team-member on API"

It would be really nice to have a concrete way to write `r?
@rust-lang/libs` or similar and have a random libs team member assigned.
That would help for such situations.

**Pull request closed without merging**
