### PR TITLE
Ping eddyb on apfloat changes

### PR DESCRIPTION
**Pull request by jhwgh1968**
@eddyb [wrote](https://github.com/rust-lang/rust/pull/83185#issuecomment-800275389):
> Can we add a rule somewhere that makes rust-highfive ping me whenever someone touches `compiler/rustc_apfloat`?

Your wish is my command! :genie_man: 

(This will also hopefully flush out any issues with my in-draft PR which takes a similar approach.)

### CODE REVIEW

**Comment by eddyb** [comment]
It... already happened (#315).

**Comment by jhwgh1968** [comment]
Oh! Sorry I missed that!

The main difference between mine an @jyn514's version is that mine is an actual warning. You know, like "these commits modify submodules."

Given that the entire point is that this section of the code is in limbo, I thought that was warranted. Still, I can close if the current version is sufficient.

**Comment by eddyb** [comment]
cc @Mark-Simulacrum I'm not sure who gets to review these PRs.

**Comment by Mark-Simulacrum** [comment]
Why is this not addable by editing the message @jyn514 added?

**Comment by jhwgh1968** [comment]
The warning message appears to be a different code path: [post_warnings](https://github.com/rust-lang/highfive/blob/accad5e765c39a931029b37738ac0be78699e1ea/highfive/newpr.py#L157) versus [post_comment](https://github.com/rust-lang/highfive/blob/accad5e765c39a931029b37738ac0be78699e1ea/highfive/newpr.py#L170). The former is what I copied from [my current WIP for compiler targets](https://github.com/rust-lang/highfive/pull/313) not seeing the other PR already done. I also did not see the latter mechanism at all, which was a mistake on my part.

Since getting @eddyb pinged was the point, and @Mark-Simulacrum's comment implies the difference is not very important (as I wondered might be the case above), I will just close this. My apologies for the wasted time!

**Pull request closed without merging**
