### PR TITLE
Fix issues

### LINKED ISSUE #213: Exception when handling custom mentions
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/highfive/app.py", line 45, in new_pr
    return handler.run(flask.request.headers['X-GitHub-Event'])
  File "/usr/local/lib/python2.7/dist-packages/highfive/newpr.py", line 71, in run
    self.new_pr()
  File "/usr/local/lib/python2.7/dist-packages/highfive/newpr.py", line 377, in new_pr
    author, to_mention
  File "/usr/local/lib/python2.7/dist-packages/highfive/newpr.py", line 133, in set_assignee
    message += "%s\n\ncc %s" % (mention['message'],
KeyError: 'message'
```

https://github.com/rust-lang/highfive/blob/748c035ca2a913cb3bc95404f8665985736f165c/highfive/newpr.py#L133-L134

@GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #213.

cc @pietroalbini

### CODE REVIEW

**Comment by pietroalbini** [comment]
A test is failing.

**Comment by GuillaumeGomez** [comment]
Ah indeed. Will take a look.

**Comment by GuillaumeGomez** [comment]
Fixed. :)

**Comment by pietroalbini** [comment]
Deployed!

**Comment by GuillaumeGomez** [comment]
Thanks! We'll see if it was the root of the bug.

**Pull request merged**
