### PR TITLE
Drop kennytm from CI review

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]
Should we also drop kenny from the libs review queue? not sure how active they've been there ...

**Comment by Mark-Simulacrum** [comment]
I think this change definitely makes sense (and it may make sense to add you), libs PR queue already moves pretty slowly in general and there is some activity there so I'm not sure it makes sense to drop at this time.

**Comment by jyn514** [comment]
> and it may make sense to add you

sure, done :) https://github.com/rust-lang/highfive/pull/417

**Comment by thomcc** [comment]
> Should we also drop kenny from the libs review queue? not sure how active they've been there ...

Pretty inactive, so IMO yes. As it is, I end up looking over their review list every so often and taking things, it would really be much better if they were just not put there in the first place.

**Pull request merged**
