### PR TITLE
Remove nrc from Cargo reviewers

### PR DESCRIPTION
**Pull request by alexcrichton**
cc @nrc, don't want to do anything you're not aware of, but also don't want to add too much to your plate!

### CODE REVIEW

**Comment by pietroalbini** [comment]
Is this ready to be merged?

**Comment by alexcrichton** [comment]
Let's give @nrc a few more days to take a look to confirm

**Comment by nrc** [comment]
Hey, sure, thanks. Sorry for neglecting my review duties.

**Comment by alexcrichton** [comment]
No worries @nrc, just didn't want to overload you any more than you already are :)

**Pull request merged**
